// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	MapAPIService := openapi.NewMapAPIService()
	MapAPIController := openapi.NewMapAPIController(MapAPIService)

	NodeAPIService := openapi.NewNodeAPIService()
	NodeAPIController := openapi.NewNodeAPIController(NodeAPIService)

	TopicAPIService := openapi.NewTopicAPIService()
	TopicAPIController := openapi.NewTopicAPIController(TopicAPIService)

	UserAPIService := openapi.NewUserAPIService()
	UserAPIController := openapi.NewUserAPIController(UserAPIService)

	router := openapi.NewRouter(MapAPIController, NodeAPIController, TopicAPIController, UserAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
