// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// NodeAPIController binds http requests to an api service and writes the service results to the http response
type NodeAPIController struct {
	service NodeAPIServicer
	errorHandler ErrorHandler
}

// NodeAPIOption for how the controller is set up.
type NodeAPIOption func(*NodeAPIController)

// WithNodeAPIErrorHandler inject ErrorHandler into controller
func WithNodeAPIErrorHandler(h ErrorHandler) NodeAPIOption {
	return func(c *NodeAPIController) {
		c.errorHandler = h
	}
}

// NewNodeAPIController creates a default api controller
func NewNodeAPIController(s NodeAPIServicer, opts ...NodeAPIOption) *NodeAPIController {
	controller := &NodeAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the NodeAPIController
func (c *NodeAPIController) Routes() Routes {
	return Routes{
		"GetNode": Route{
			strings.ToUpper("Get"),
			"/api/v1/node",
			c.GetNode,
		},
		"AddNode": Route{
			strings.ToUpper("Post"),
			"/api/v1/node",
			c.AddNode,
		},
		"DeleteNode": Route{
			strings.ToUpper("Delete"),
			"/api/v1/node",
			c.DeleteNode,
		},
		"GetNodeNextBattleTested": Route{
			strings.ToUpper("Get"),
			"/api/v1/node/nextBattleTested",
			c.GetNodeNextBattleTested,
		},
		"GetNodeNextFresh": Route{
			strings.ToUpper("Get"),
			"/api/v1/node/nextFresh",
			c.GetNodeNextFresh,
		},
		"UpdateNodeTitle": Route{
			strings.ToUpper("Put"),
			"/api/v1/node/title",
			c.UpdateNodeTitle,
		},
		"UpdateNodeVideoVote": Route{
			strings.ToUpper("Put"),
			"/api/v1/node/videoVote",
			c.UpdateNodeVideoVote,
		},
		"UpdateNodeVideoEdit": Route{
			strings.ToUpper("Put"),
			"/api/v1/node/videoEdit",
			c.UpdateNodeVideoEdit,
		},
		"UpdateNodeBattleVote": Route{
			strings.ToUpper("Put"),
			"/api/v1/node/battleVote",
			c.UpdateNodeBattleVote,
		},
		"UpdateNodeFreshVote": Route{
			strings.ToUpper("Put"),
			"/api/v1/node/freshVote",
			c.UpdateNodeFreshVote,
		},
		"UpdateNodeFlag": Route{
			strings.ToUpper("Put"),
			"/api/v1/node/flag",
			c.UpdateNodeFlag,
		},
	}
}

// GetNode - get wiki node
func (c *NodeAPIController) GetNode(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var nodeIdParam string
	if query.Has("nodeId") {
		param := query.Get("nodeId")

		nodeIdParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "nodeId"}, nil)
		return
	}
	var tidParam string
	if query.Has("tid") {
		param := query.Get("tid")

		tidParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "tid"}, nil)
		return
	}
	result, err := c.service.GetNode(r.Context(), nodeIdParam, tidParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// AddNode - Add a new node
func (c *NodeAPIController) AddNode(w http.ResponseWriter, r *http.Request) {
	nodeDataParam := NodeData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&nodeDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertNodeDataRequired(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertNodeDataConstraints(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AddNode(r.Context(), nodeDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteNode - Delete a node
func (c *NodeAPIController) DeleteNode(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var nodeIdParam string
	if query.Has("nodeId") {
		param := query.Get("nodeId")

		nodeIdParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "nodeId"}, nil)
		return
	}
	var tidParam string
	if query.Has("tid") {
		param := query.Get("tid")

		tidParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "tid"}, nil)
		return
	}
	result, err := c.service.DeleteNode(r.Context(), nodeIdParam, tidParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetNodeNextBattleTested - get next top battle tested ID
func (c *NodeAPIController) GetNodeNextBattleTested(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var nodeIdParam string
	if query.Has("nodeId") {
		param := query.Get("nodeId")

		nodeIdParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "nodeId"}, nil)
		return
	}
	var tidParam string
	if query.Has("tid") {
		param := query.Get("tid")

		tidParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "tid"}, nil)
		return
	}
	result, err := c.service.GetNodeNextBattleTested(r.Context(), nodeIdParam, tidParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetNodeNextFresh - get next top fresh ID
func (c *NodeAPIController) GetNodeNextFresh(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var nodeIdParam string
	if query.Has("nodeId") {
		param := query.Get("nodeId")

		nodeIdParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "nodeId"}, nil)
		return
	}
	var tidParam string
	if query.Has("tid") {
		param := query.Get("tid")

		tidParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "tid"}, nil)
		return
	}
	result, err := c.service.GetNodeNextFresh(r.Context(), nodeIdParam, tidParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// UpdateNodeTitle - Update a nodes title and description
func (c *NodeAPIController) UpdateNodeTitle(w http.ResponseWriter, r *http.Request) {
	nodeDataParam := NodeData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&nodeDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertNodeDataRequired(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertNodeDataConstraints(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateNodeTitle(r.Context(), nodeDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// UpdateNodeVideoVote - Update a nodes video votes
func (c *NodeAPIController) UpdateNodeVideoVote(w http.ResponseWriter, r *http.Request) {
	nodeDataParam := NodeData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&nodeDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertNodeDataRequired(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertNodeDataConstraints(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateNodeVideoVote(r.Context(), nodeDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// UpdateNodeVideoEdit - add or remove videos from a node
func (c *NodeAPIController) UpdateNodeVideoEdit(w http.ResponseWriter, r *http.Request) {
	nodeDataParam := NodeData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&nodeDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertNodeDataRequired(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertNodeDataConstraints(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateNodeVideoEdit(r.Context(), nodeDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// UpdateNodeBattleVote - battle vote a node
func (c *NodeAPIController) UpdateNodeBattleVote(w http.ResponseWriter, r *http.Request) {
	nodeDataParam := NodeData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&nodeDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertNodeDataRequired(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertNodeDataConstraints(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateNodeBattleVote(r.Context(), nodeDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// UpdateNodeFreshVote - fresh vote a node
func (c *NodeAPIController) UpdateNodeFreshVote(w http.ResponseWriter, r *http.Request) {
	nodeDataParam := NodeData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&nodeDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertNodeDataRequired(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertNodeDataConstraints(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateNodeFreshVote(r.Context(), nodeDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// UpdateNodeFlag - fresh vote a node
func (c *NodeAPIController) UpdateNodeFlag(w http.ResponseWriter, r *http.Request) {
	nodeDataParam := NodeData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&nodeDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertNodeDataRequired(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertNodeDataConstraints(nodeDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateNodeFlag(r.Context(), nodeDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
