// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// AllAPIService is a service that implements the logic for the AllAPIServicer
// This service should implement the business logic for every endpoint for the AllAPI API.
// Include any external packages or services that will be required by this service.
type AllAPIService struct {
}

// NewAllAPIService creates a default api service
func NewAllAPIService() *AllAPIService {
	return &AllAPIService{}
}

// ClipImage - gets clip image
func (s *AllAPIService) ClipImage(ctx context.Context, clipUrl string) (ImplResponse, error) {
	// TODO - update ClipImage with the required logic for this service method.
	// Add api_all_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, string{}) or use other options such as http.Ok ...
	// return Response(200, string{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClipImage method not implemented")
}
