// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// NodeAPIService is a service that implements the logic for the NodeAPIServicer
// This service should implement the business logic for every endpoint for the NodeAPI API.
// Include any external packages or services that will be required by this service.
type NodeAPIService struct {
}

// NewNodeAPIService creates a default api service
func NewNodeAPIService() *NodeAPIService {
	return &NodeAPIService{}
}

// GetNode - get wiki node
func (s *NodeAPIService) GetNode(ctx context.Context, nodeId string, tid string) (ImplResponse, error) {
	// TODO - update GetNode with the required logic for this service method.
	// Add api_node_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, NodeData{}) or use other options such as http.Ok ...
	// return Response(200, NodeData{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetNode method not implemented")
}

// AddNode - Add a new node
func (s *NodeAPIService) AddNode(ctx context.Context, nodeData NodeData) (ImplResponse, error) {
	// TODO - update AddNode with the required logic for this service method.
	// Add api_node_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ResponsePostNode{}) or use other options such as http.Ok ...
	// return Response(200, ResponsePostNode{}), nil

	// TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	// return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddNode method not implemented")
}

// DeleteNode - Delete a node
func (s *NodeAPIService) DeleteNode(ctx context.Context, nodeId string, tid string) (ImplResponse, error) {
	// TODO - update DeleteNode with the required logic for this service method.
	// Add api_node_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(403, {}) or use other options such as http.Ok ...
	// return Response(403, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteNode method not implemented")
}

// UpdateNodeTitle - Update a nodes title and description
func (s *NodeAPIService) UpdateNodeTitle(ctx context.Context, nodeData NodeData) (ImplResponse, error) {
	// TODO - update UpdateNodeTitle with the required logic for this service method.
	// Add api_node_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, bool{}) or use other options such as http.Ok ...
	// return Response(200, bool{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	// return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateNodeTitle method not implemented")
}

// UpdateNodeVideoVote - Update a nodes video votes
func (s *NodeAPIService) UpdateNodeVideoVote(ctx context.Context, nodeData NodeData) (ImplResponse, error) {
	// TODO - update UpdateNodeVideoVote with the required logic for this service method.
	// Add api_node_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, int32{}) or use other options such as http.Ok ...
	// return Response(200, int32{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	// return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateNodeVideoVote method not implemented")
}

// UpdateNodeVideoEdit - add or remove videos from a node
func (s *NodeAPIService) UpdateNodeVideoEdit(ctx context.Context, nodeData NodeData) (ImplResponse, error) {
	// TODO - update UpdateNodeVideoEdit with the required logic for this service method.
	// Add api_node_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	// return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateNodeVideoEdit method not implemented")
}

// UpdateNodeBattleVote - battle vote a node
func (s *NodeAPIService) UpdateNodeBattleVote(ctx context.Context, nodeData NodeData) (ImplResponse, error) {
	// TODO - update UpdateNodeBattleVote with the required logic for this service method.
	// Add api_node_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, int32{}) or use other options such as http.Ok ...
	// return Response(200, int32{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	// return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateNodeBattleVote method not implemented")
}

// UpdateNodeFreshVote - fresh vote a node
func (s *NodeAPIService) UpdateNodeFreshVote(ctx context.Context, nodeData NodeData) (ImplResponse, error) {
	// TODO - update UpdateNodeFreshVote with the required logic for this service method.
	// Add api_node_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, int32{}) or use other options such as http.Ok ...
	// return Response(200, int32{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	// return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateNodeFreshVote method not implemented")
}

// UpdateNodeFlag - fresh vote a node
func (s *NodeAPIService) UpdateNodeFlag(ctx context.Context, nodeData NodeData) (ImplResponse, error) {
	// TODO - update UpdateNodeFlag with the required logic for this service method.
	// Add api_node_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	// return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateNodeFlag method not implemented")
}
