// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
	"time"

	"github.com/go-pkgz/lgr"

	bolt "go.etcd.io/bbolt"
	"github.com/SpyLime/flowBackend/clock"
)

// TopicAPIService is a service that implements the logic for the TopicAPIServicer
// This service should implement the business logic for every endpoint for the TopicAPI API.
// Include any external packages or services that will be required by this service.
type TopicAPIService struct {
	db    *bolt.DB
	clock clock.Clock
}

// NewTopicAPIService creates a default api service
func NewTopicAPIService(db *bolt.DB, clock clock.Clock) *TopicAPIService {
	return &TopicAPIService{
		db: db,
        clock: clock,
	}
}

// GetTopics - get all topics
func (s *TopicAPIService) GetTopics(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetTopics with the required logic for this service method.
	// Add api_topic_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []GetTopics200ResponseInner{}) or use other options such as http.Ok ...
	lgr.Printf("INFO get topics")
	items := []GetTopics200ResponseInner{
		{
			Id: time.Now(),
			Title: "bjj0",
		},
		{
			Id: time.Now().Add(1),
			Title: "bjj1",
		},{
			Id: time.Now().Add(2),
			Title: "bjj2",
		},{
			Id: time.Now().Add(3),
			Title: "bjj3",
		},{
			Id: time.Now().Add(4),
			Title: "bjj4",
		},{
			Id: time.Now().Add(5),
			Title: "bjj5",
		},

	}
	return Response(200, items), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// return Response(http.StatusNotImplemented, nil), errors.New("GetTopics method not implemented")
}

// UpdateTopic - Update an existing topic
func (s *TopicAPIService) UpdateTopic(ctx context.Context, getTopics200ResponseInner GetTopics200ResponseInner) (ImplResponse, error) {
	// TODO - update UpdateTopic with the required logic for this service method.
	// Add api_topic_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	// return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateTopic method not implemented")
}

// AddTopic - Add a new topic
func (s *TopicAPIService) AddTopic(ctx context.Context, getTopics200ResponseInner GetTopics200ResponseInner) (ImplResponse, error) {
	// TODO - update AddTopic with the required logic for this service method.
	// Add api_topic_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AddTopic200Response{}) or use other options such as http.Ok ...
	// return Response(200, AddTopic200Response{}), nil

	// TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	// return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddTopic method not implemented")
}

// DeleteTopic - Delete a node
func (s *TopicAPIService) DeleteTopic(ctx context.Context, topicId string) (ImplResponse, error) {
	// TODO - update DeleteTopic with the required logic for this service method.
	// Add api_topic_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(403, {}) or use other options such as http.Ok ...
	// return Response(403, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteTopic method not implemented")
}
