// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi


import (
	"time"
)



type RequestPostNode struct {

	Source time.Time `json:"source"`

	Target time.Time `json:"target"`

	Topic string `json:"topic"`
}

// AssertRequestPostNodeRequired checks if the required fields are not zero-ed
func AssertRequestPostNodeRequired(obj RequestPostNode) error {
	elements := map[string]interface{}{
		"source": obj.Source,
		"target": obj.Target,
		"topic": obj.Topic,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRequestPostNodeConstraints checks if the values respects the defined constraints
func AssertRequestPostNodeConstraints(obj RequestPostNode) error {
	return nil
}
