// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi


import (
	"time"
)



type LinkData struct {

	Link string `json:"link,omitempty"`

	Votes int32 `json:"votes,omitempty"`

	AddedBy AddTopic200ResponseNodeDataYoutubeLinksInnerAddedBy `json:"addedBy,omitempty"`

	DateAdded time.Time `json:"dateAdded,omitempty"`
}

// AssertLinkDataRequired checks if the required fields are not zero-ed
func AssertLinkDataRequired(obj LinkData) error {
	if err := AssertAddTopic200ResponseNodeDataYoutubeLinksInnerAddedByRequired(obj.AddedBy); err != nil {
		return err
	}
	return nil
}

// AssertLinkDataConstraints checks if the values respects the defined constraints
func AssertLinkDataConstraints(obj LinkData) error {
	if err := AssertAddTopic200ResponseNodeDataYoutubeLinksInnerAddedByConstraints(obj.AddedBy); err != nil {
		return err
	}
	return nil
}
