// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi


import (
	"time"
)



type AddNode200Response struct {

	TargetId time.Time `json:"targetId"`

	SourceId time.Time `json:"sourceId"`
}

// AssertAddNode200ResponseRequired checks if the required fields are not zero-ed
func AssertAddNode200ResponseRequired(obj AddNode200Response) error {
	elements := map[string]interface{}{
		"targetId": obj.TargetId,
		"sourceId": obj.SourceId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAddNode200ResponseConstraints checks if the values respects the defined constraints
func AssertAddNode200ResponseConstraints(obj AddNode200Response) error {
	return nil
}
