// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi


import (
	"time"
)



type ResponsePostNode struct {

	TargetId time.Time `json:"targetId"`

	SourceId time.Time `json:"sourceId"`
}

// AssertResponsePostNodeRequired checks if the required fields are not zero-ed
func AssertResponsePostNodeRequired(obj ResponsePostNode) error {
	elements := map[string]interface{}{
		"targetId": obj.TargetId,
		"sourceId": obj.SourceId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertResponsePostNodeConstraints checks if the values respects the defined constraints
func AssertResponsePostNodeConstraints(obj ResponsePostNode) error {
	return nil
}
