// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi




type AuthUser404Response struct {

	IsAuth bool `json:"isAuth,omitempty"`

	Error bool `json:"error,omitempty"`
}

// AssertAuthUser404ResponseRequired checks if the required fields are not zero-ed
func AssertAuthUser404ResponseRequired(obj AuthUser404Response) error {
	return nil
}

// AssertAuthUser404ResponseConstraints checks if the values respects the defined constraints
func AssertAuthUser404ResponseConstraints(obj AuthUser404Response) error {
	return nil
}
