// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi




type AddTopic200ResponseNodeDataYoutubeLinksInnerAddedBy struct {

	Username string `json:"username,omitempty"`

	Id string `json:"id,omitempty"`
}

// AssertAddTopic200ResponseNodeDataYoutubeLinksInnerAddedByRequired checks if the required fields are not zero-ed
func AssertAddTopic200ResponseNodeDataYoutubeLinksInnerAddedByRequired(obj AddTopic200ResponseNodeDataYoutubeLinksInnerAddedBy) error {
	return nil
}

// AssertAddTopic200ResponseNodeDataYoutubeLinksInnerAddedByConstraints checks if the values respects the defined constraints
func AssertAddTopic200ResponseNodeDataYoutubeLinksInnerAddedByConstraints(obj AddTopic200ResponseNodeDataYoutubeLinksInnerAddedBy) error {
	return nil
}
