// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi


import (
	"time"
)



type FlowNode struct {

	Id time.Time `json:"id,omitempty"`

	Position FlowNodePosition `json:"position,omitempty"`

	Type string `json:"type,omitempty"`

	TargetPosition string `json:"targetPosition,omitempty"`

	SourcePosition string `json:"SourcePosition,omitempty"`

	Data FlowNodeData `json:"data,omitempty"`
}

// AssertFlowNodeRequired checks if the required fields are not zero-ed
func AssertFlowNodeRequired(obj FlowNode) error {
	if err := AssertFlowNodePositionRequired(obj.Position); err != nil {
		return err
	}
	if err := AssertFlowNodeDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertFlowNodeConstraints checks if the values respects the defined constraints
func AssertFlowNodeConstraints(obj FlowNode) error {
	if err := AssertFlowNodePositionConstraints(obj.Position); err != nil {
		return err
	}
	if err := AssertFlowNodeDataConstraints(obj.Data); err != nil {
		return err
	}
	return nil
}
