// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi




type LoginUserRequest struct {

	SsoProvider string `json:"ssoProvider,omitempty"`
}

// AssertLoginUserRequestRequired checks if the required fields are not zero-ed
func AssertLoginUserRequestRequired(obj LoginUserRequest) error {
	return nil
}

// AssertLoginUserRequestConstraints checks if the values respects the defined constraints
func AssertLoginUserRequestConstraints(obj LoginUserRequest) error {
	return nil
}
