// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi


import (
	"time"
)



type AddTopic200ResponseNodeDataYoutubeLinksInner struct {

	Link string `json:"link,omitempty"`

	Votes int32 `json:"votes,omitempty"`

	AddedBy string `json:"addedBy,omitempty"`

	DateAdded time.Time `json:"dateAdded,omitempty"`
}

// AssertAddTopic200ResponseNodeDataYoutubeLinksInnerRequired checks if the required fields are not zero-ed
func AssertAddTopic200ResponseNodeDataYoutubeLinksInnerRequired(obj AddTopic200ResponseNodeDataYoutubeLinksInner) error {
	return nil
}

// AssertAddTopic200ResponseNodeDataYoutubeLinksInnerConstraints checks if the values respects the defined constraints
func AssertAddTopic200ResponseNodeDataYoutubeLinksInnerConstraints(obj AddTopic200ResponseNodeDataYoutubeLinksInner) error {
	return nil
}
