// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi




type FlowNodePosition struct {

	X int32 `json:"x,omitempty"`

	Y int32 `json:"y,omitempty"`
}

// AssertFlowNodePositionRequired checks if the required fields are not zero-ed
func AssertFlowNodePositionRequired(obj FlowNodePosition) error {
	return nil
}

// AssertFlowNodePositionConstraints checks if the values respects the defined constraints
func AssertFlowNodePositionConstraints(obj FlowNodePosition) error {
	return nil
}
