// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi




type ResponsePostTopic struct {

	Topic Topic `json:"topic"`

	NodeData NodeData `json:"nodeData"`
}

// AssertResponsePostTopicRequired checks if the required fields are not zero-ed
func AssertResponsePostTopicRequired(obj ResponsePostTopic) error {
	elements := map[string]interface{}{
		"topic": obj.Topic,
		"nodeData": obj.NodeData,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertResponsePostTopicConstraints checks if the values respects the defined constraints
func AssertResponsePostTopicConstraints(obj ResponsePostTopic) error {
	return nil
}
