// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi




type GetMapById200ResponseNodesInner struct {

	Id string `json:"id,omitempty"`

	Position GetMapById200ResponseNodesInnerPosition `json:"position,omitempty"`

	Type string `json:"type,omitempty"`

	TargetPosition string `json:"targetPosition,omitempty"`

	SourcePosition string `json:"SourcePosition,omitempty"`

	Data GetMapById200ResponseNodesInnerData `json:"data,omitempty"`
}

// AssertGetMapById200ResponseNodesInnerRequired checks if the required fields are not zero-ed
func AssertGetMapById200ResponseNodesInnerRequired(obj GetMapById200ResponseNodesInner) error {
	if err := AssertGetMapById200ResponseNodesInnerPositionRequired(obj.Position); err != nil {
		return err
	}
	if err := AssertGetMapById200ResponseNodesInnerDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertGetMapById200ResponseNodesInnerConstraints checks if the values respects the defined constraints
func AssertGetMapById200ResponseNodesInnerConstraints(obj GetMapById200ResponseNodesInner) error {
	if err := AssertGetMapById200ResponseNodesInnerPositionConstraints(obj.Position); err != nil {
		return err
	}
	if err := AssertGetMapById200ResponseNodesInnerDataConstraints(obj.Data); err != nil {
		return err
	}
	return nil
}
