// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi




type Login struct {

	SsoProvider string `json:"ssoProvider,omitempty"`
}

// AssertLoginRequired checks if the required fields are not zero-ed
func AssertLoginRequired(obj Login) error {
	return nil
}

// AssertLoginConstraints checks if the values respects the defined constraints
func AssertLoginConstraints(obj Login) error {
	return nil
}
