// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi




type GetTopics200ResponseInner struct {

	Title string `json:"title"`
}

// AssertGetTopics200ResponseInnerRequired checks if the required fields are not zero-ed
func AssertGetTopics200ResponseInnerRequired(obj GetTopics200ResponseInner) error {
	elements := map[string]interface{}{
		"title": obj.Title,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertGetTopics200ResponseInnerConstraints checks if the values respects the defined constraints
func AssertGetTopics200ResponseInnerConstraints(obj GetTopics200ResponseInner) error {
	return nil
}
