// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi


import (
	"time"
)



type RequestNode struct {

	NodeId time.Time `json:"nodeId,omitempty"`

	Tid time.Time `json:"tid,omitempty"`
}

// AssertRequestNodeRequired checks if the required fields are not zero-ed
func AssertRequestNodeRequired(obj RequestNode) error {
	return nil
}

// AssertRequestNodeConstraints checks if the values respects the defined constraints
func AssertRequestNodeConstraints(obj RequestNode) error {
	return nil
}
