// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi


import (
	"time"
)



type GetMapById200ResponseEdgesInner struct {

	Id string `json:"id,omitempty"`

	Source time.Time `json:"source,omitempty"`

	Target time.Time `json:"target,omitempty"`
}

// AssertGetMapById200ResponseEdgesInnerRequired checks if the required fields are not zero-ed
func AssertGetMapById200ResponseEdgesInnerRequired(obj GetMapById200ResponseEdgesInner) error {
	return nil
}

// AssertGetMapById200ResponseEdgesInnerConstraints checks if the values respects the defined constraints
func AssertGetMapById200ResponseEdgesInnerConstraints(obj GetMapById200ResponseEdgesInner) error {
	return nil
}
