// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi




type GetMapById200ResponseNodesInnerPosition struct {

	X int32 `json:"x,omitempty"`

	Y int32 `json:"y,omitempty"`
}

// AssertGetMapById200ResponseNodesInnerPositionRequired checks if the required fields are not zero-ed
func AssertGetMapById200ResponseNodesInnerPositionRequired(obj GetMapById200ResponseNodesInnerPosition) error {
	return nil
}

// AssertGetMapById200ResponseNodesInnerPositionConstraints checks if the values respects the defined constraints
func AssertGetMapById200ResponseNodesInnerPositionConstraints(obj GetMapById200ResponseNodesInnerPosition) error {
	return nil
}
