// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi


import (
	"time"
)



type GetNodeNodeInfoParameter struct {

	NodeId time.Time `json:"nodeId,omitempty"`

	Tid time.Time `json:"tid,omitempty"`
}

// AssertGetNodeNodeInfoParameterRequired checks if the required fields are not zero-ed
func AssertGetNodeNodeInfoParameterRequired(obj GetNodeNodeInfoParameter) error {
	return nil
}

// AssertGetNodeNodeInfoParameterConstraints checks if the values respects the defined constraints
func AssertGetNodeNodeInfoParameterConstraints(obj GetNodeNodeInfoParameter) error {
	return nil
}
