// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi




type FlowNodeData struct {

	Title string `json:"title,omitempty"`

	BattleTested int32 `json:"battleTested,omitempty"`

	Fresh int32 `json:"fresh,omitempty"`

	Speed int32 `json:"speed,omitempty"`
}

// AssertFlowNodeDataRequired checks if the required fields are not zero-ed
func AssertFlowNodeDataRequired(obj FlowNodeData) error {
	return nil
}

// AssertFlowNodeDataConstraints checks if the values respects the defined constraints
func AssertFlowNodeDataConstraints(obj FlowNodeData) error {
	return nil
}
