// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi


import (
	"time"
)



type NodeData struct {

	Id time.Time `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Topic time.Time `json:"topic,omitempty"`

	BattleTested int32 `json:"battleTested,omitempty"`

	Fresh int32 `json:"fresh,omitempty"`

	Speed int32 `json:"speed,omitempty"`

	Description string `json:"description,omitempty"`

	IsFlagged bool `json:"isFlagged,omitempty"`

	YoutubeLinks []AddTopic200ResponseNodeDataYoutubeLinksInner `json:"youtubeLinks,omitempty"`

	CreatedBy string `json:"createdBy,omitempty"`

	EditedBy []string `json:"editedBy,omitempty"`
}

// AssertNodeDataRequired checks if the required fields are not zero-ed
func AssertNodeDataRequired(obj NodeData) error {
	for _, el := range obj.YoutubeLinks {
		if err := AssertAddTopic200ResponseNodeDataYoutubeLinksInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertNodeDataConstraints checks if the values respects the defined constraints
func AssertNodeDataConstraints(obj NodeData) error {
	for _, el := range obj.YoutubeLinks {
		if err := AssertAddTopic200ResponseNodeDataYoutubeLinksInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
