// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi




type GetMapById200ResponseNodesInnerData struct {

	Title string `json:"title,omitempty"`

	BattleTested int64 `json:"battleTested,omitempty"`

	Fresh int64 `json:"fresh,omitempty"`

	Speed int32 `json:"speed,omitempty"`
}

// AssertGetMapById200ResponseNodesInnerDataRequired checks if the required fields are not zero-ed
func AssertGetMapById200ResponseNodesInnerDataRequired(obj GetMapById200ResponseNodesInnerData) error {
	return nil
}

// AssertGetMapById200ResponseNodesInnerDataConstraints checks if the values respects the defined constraints
func AssertGetMapById200ResponseNodesInnerDataConstraints(obj GetMapById200ResponseNodesInnerData) error {
	return nil
}
