// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Flow Learning - OpenAPI 3.1
 *
 * api for flow learning
 *
 * API version: 1.0.0
 * Contact: floTeam@gmail.com
 */

package openapi




type UserIdentifier struct {

	Username string `json:"username,omitempty"`

	Id string `json:"id,omitempty"`
}

// AssertUserIdentifierRequired checks if the required fields are not zero-ed
func AssertUserIdentifierRequired(obj UserIdentifier) error {
	return nil
}

// AssertUserIdentifierConstraints checks if the values respects the defined constraints
func AssertUserIdentifierConstraints(obj UserIdentifier) error {
	return nil
}
